fs: ntfs3: Use size_add instead of size_add_new
ntfs_fs.h:471:9: error: implicit declaration of function 'size_add_new' [-Werror,-Wimplicit-function-declaration]
        return size_add_new(size, 1023) & ~(size_t)1023;

xattr.c:117:17: error: implicit declaration of function 'size_add_new' [-Werror,-Wimplicit-function-declaration]
        ea_p = kmalloc(size_add_new(size, add_bytes), GFP_NOFS);